### PR TITLE
Help tab links (inside and outside of courses) customized.

### PR DESCRIPTION
**Pull request by diegomillan**
### Description

This PR is a theme customization in order to include links to CME support center portal and CME help ticket form. Works together with [this](https://github.com/Stanford-Online/edx-platform/pull/534) PR.
### Reviewers

If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] Code review: @stvstnfrd
- [x] Code review: @felipemontoya

FYI: Tag anyone who might be interested in this PR here

@juancamilom
### Post-review
- [x] Rebase and squash commits

### CODE REVIEW

**Comment by felipemontoya** [comment]
:+1: @stvstnfrd ready for your feedback here

**Comment by stvstnfrd** [comment]
@diegomillan @felipemontoya 

Much like the copyright/footer PR, forking the template here is too
broad an instrument.

There is a setting in configuration, `EDXAPP_HELP_MODAL_LINKS` that is
used to populate the list of links. It defaults to:

``` yaml
EDXAPP_HELP_MODAL_LINKS:
  - 'url': 'https://stanfordonline.zendesk.com/hc/en-us/articles/202275024-How-do-I-create-an-account-'
    'text': 'How to register an account'
  - 'url': 'https://stanfordonline.zendesk.com/hc/en-us/articles/201864484-How-do-I-reset-my-password-'
    'text': 'How to reset a password'
  - 'url': 'https://stanfordonline.zendesk.com/hc/en-us/articles/203009244-How-do-I-enroll-in-a-course-'
    'text': 'How to enroll in a course'
```

I see that your copy/pasted code does reference these values;
I thought this was part of what Mark wanted customized?

For any links that are not already customized (notably "Access the Help
Center"), you should make that specific bit of text customizable and
overridden via JSON/settings (as is done above), instead of copy/pasting
the entire file. Note: this may require new configuration settings.

Given that we maintain 3 separate instances, forking and retheming this
entire file for every deployment (its contents are nontrivial, including
javascript, etc.), just to customize the links, would cause maintenance
headaches.

To that point, it looks like this isn't "just" a copy-paste, but instead
it incorrectly hard-codes values that mustn't be. There are at least a
couple of strings that hard-code "CME", where they should instead
reference `{platform_name}`. Otherwise, we're presented with yet another
maintenance burden.

**Comment by felipemontoya** [comment]
@stvstnfrd, here the issue is very similar to the maintainability requirement at #5, so I'll wait until we find a solution there to update this.

**Comment by stvstnfrd** [comment]
@felipemontoya One difference between this and #5 is that _hopefully_ we can avoid theming any file at all. We're already pulling the 3 main links from a configuration setting and ideally, we can do the same for the other link(s). Or is there a more complicated customization here?

**Comment by diegomillan** [comment]
Hi @stvstnfrd, we have updated this PR and we are ready for your feedback here. Please note that it works along with another PR made to  edx-platform.

**Comment by felipemontoya** [comment]
Expanding on what Diego said, we tried to make the required changes for CME, but keep the maintenance overhead to a minimum. We still had to extract and theme 2 interactions that we were not able to modify using the `EDXAPP_HELP_MODAL_LINKS`.

In order for this changes to work, we would also need https://github.com/Stanford-Online/edx-platform/pull/534 to be merged at the platform repo.

@stvstnfrd we kept the same logic as per your feedback in other PRs, only extend and change the part of the templates we needed to modify, and avoid using configuration variables where the only use would be in a themed file.

I think we are good here from my perspective :+1:

**Comment by felipemontoya** [comment]
Hello @stvstnfrd, since [PR 534](https://github.com/Stanford-Online/edx-platform/pull/534) has been merged, this PR is ready to be merged any time.

**Pull request merged**
