### PR TITLE
Fixing url references for cme theme

### PR DESCRIPTION
**Pull request by diegomillan**
Hotfix
### Description

This PR is just a fix for wrong url references. We used this as a base for upcoming PRs.
### Reviewers

If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [x] Code review: @stvstnfrd
- [x] Code review: @caesar2164 
- [x] Code review: @felipemontoya

FYI: Tag anyone who might be interested in this PR here

@juancamilom
### Post-review
- [ ] Rebase and squash commits

### CODE REVIEW

**Comment by felipemontoya** [comment]
Hi @stvstnfrd, now on the right repo. :+1: by me, and also this is something we noticed, that failed for us on devstack, and has not been a problem yet since the cme instance is still using the suclass theme.

Anyway, please take a look when you have the chance

**Review by felipemontoya — APPROVED** [review]

**Comment by stvstnfrd** [comment]
This looks good to me; @caesar2164 ?

**Comment by caesar2164** [comment]
derp, yeah this is good!

**Comment by caesar2164** [comment]
👍

**Comment by stvstnfrd** [comment]
@diegomillan @felipemontoya We're all +1 here on this. It doesn't look like anything really needs squashed, but let us know if/when you're ready to merge and we'll hit the button.

**Comment by diegomillan** [comment]
We are ready to merge @stvstnfrd @caesar2164 @felipemontoya

**Pull request merged**
